receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
#      - action: insert
#        key: loki.format
#        value: raw
      - action: insert
        key: loki.resource.labels
        value: app, runtime
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/tempo ]  
    logs:
      receivers: [ otlp ]
      processors: [ batch, resource ]
      exporters: [ loki ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
